version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hermes-webui-umbrel_app_1
      APP_PORT: "8787"

  app:
    image: ghcr.io/nesquena/hermes-webui:latest@sha256:2c0691fc30e2688b48b7defbc673d197f09f5e2285e4e0dc55cc83d010f5a335
    user: "1000:1000"
    restart: unless-restarted
    environment:
      HERMES_WEBUI_HOST: "0.0.0.0"
      HERMES_WEBUI_PORT: "8787"
      HERMES_WEBUI_STATE_DIR: /home/hermeswebui/.hermes/webui
      HERMES_WEBUI_DEFAULT_WORKSPACE: /workspace
    volumes:
      - ${APP_DATA_DIR}/data/hermes-home:/home/hermeswebui/.hermes
      - ${APP_DATA_DIR}/data/workspace:/workspace
